# Module: beat
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/7.x/metricbeat-module-beat.html
#metricbeat.modules:
- module: beat
  metricsets:
    - stats
    - state
  period: 10s
  hosts: ["http://localhost:5066"]

