# Module: docker
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/7.x/metricbeat-module-docker.html
#metricbeat.modules:
- module: docker
  metricsets:
    - container
    - cpu
    - diskio
    - event
    - healthcheck
    - info
    - memory
    - network
    - network_summary
  period: 10s
  hosts: ["unix:///var/run/docker.sock"]
  enabled: true

  # If set to true, replace dots in labels with `_`.
  labels.dedot: true

  # To connect to Docker over TLS you must specify a client and CA certificate.
  #ssl:
    #certificate_authority: "/etc/pki/root/ca.pem"
    #certificate:           "/etc/pki/client/cert.pem"
    #key:                   "/etc/pki/client/cert.key"
