# Module: nginx
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/7.x/metricbeat-module-nginx.html
#metricbeat.modules:
- module: nginx
  metricsets:
    - stubstatus
  period: 10s
  enabled: true
  # Nginx hosts
  hosts: ["http://localhost:80"]

  # Path to server status. Default nginx_status
  server_status_path: "nginx_status"

  #username: "user"
  #password: "secret"
