---
- name: testing download with get_url module
  hosts: jbox
  tasks:

    - name: download auditbeat rpm file
      get_url:
        url: https://artifacts.elastic.co/downloads/beats/auditbeat/auditbeat-8.3.3-x86_64.rpm
        dest: /home/minion/ansible/roles/auditbeat/files/
        force: true
        
...
